import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header, { IMenu, IMenuFunc } from "../components/Header";
import { icons } from "@/constant/header-icons";
import "./../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const menu: IMenu = {
		left: null,
		center: null,
		right: icons.HAMBERGER,
	};

	const func: IMenuFunc = {
		left_func: undefined,
		right_func: undefined,
	};

	return (
		<html lang="en">
			<body className={inter.className}>
				<Header menu={menu} func={func} />
				<div>{children}</div>
			</body>
		</html>
	);
}
